kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-app
  namespace: hr-staging
  labels:
    app: web-app
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: web-app
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: ###DockerRepositoryTag###/###DockerImageTag###
        ports:
        - name: web-app
          containerPort: 9060
        resources:
          requests:
            memory: 128Mi
            cpu: 0.2
          limits:
            memory: 512Mi
            cpu: 0.4
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 130
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 1
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          # desynchronize readiness and liveness probes to avoid Exceptions from the application
          initialDelaySeconds: 140
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 1
          successThreshold: 1
